### ISSUE TITLE
Prompted for credentials

### ISSUE THREAD

**Issue by los93sol** [pysco68/Pysco68.Owin.Authentication.Ntlm#10]
I'm having an issue where the first time the user is authenticated they are being prompted for credentials instead of the browser simply passing them along behind the scenes.  I am fairly new to Owin in general and don't fully understand all of the concepts yet so I'm assuming this is probably something I'm missing.

**Comment by pysco68** [comment]
This could depend on your browser's configuration. Any possibility you tested this with something else than IE?
