### ISSUE TITLE
Authorization header always missing

### ISSUE THREAD

**Issue by jpsullivan** [pysco68/Pysco68.Owin.Authentication.Ntlm#11]
Hello, thanks for releasing this cool project! I've spent a decent amount of time adding it into my own project, but I can't ever seem to get the point where it actually evaluates the NTLM challenge because `Request.Headers["Authorization"]` always returns null.

The only thing that I am doing is initiating the challenge much like an external login provider would (there's a "Windows" button on my login page), but otherwise everything else is pretty straight forward. Doing so should remove the need for me to create a separate "ntlmlogin" route, correct?

Here's a screenshot of what I'm working with.

![ntlm-not-working](https://cloud.githubusercontent.com/assets/570899/18317381/edf2eb2c-74eb-11e6-984d-79c13aea605d.png)

And here's everything related to this in my startup code:

```csharp
app.SetDefaultSignInAsAuthenticationType(DefaultAuthenticationTypes.ApplicationCookie);

app.UseCookieAuthentication(new CookieAuthenticationOptions
{
    AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
    AuthenticationMode = AuthenticationMode.Active,
    LoginPath = new PathString("/account/login"),
    Provider = new CookieAuthenticationProvider()
    {
        OnApplyRedirect = ctx =>
        {
            // do not show the login form for unauthorized api requests, ajax requests or ntlm challenges
            if (!ctx.Request.IsApiRequest() || !ctx.Request.IsAjaxRequest() || !ctx.Request.IsNtlmAuthenticationCallback())
            {
                ctx.Response.Redirect(ctx.RedirectUri);
            }
        },
        // Enables the application to validate the security stamp when the user logs in.
        // This is a security feature which is used when you change a password or add an external login to your account.  
        OnValidateIdentity = SecurityStampValidator.OnValidateIdentity<MyUserManager, User, int>(
            validateInterval: TimeSpan.FromMinutes(30),
            regenerateIdentityCallback: (manager, user) => IdentityHelpers.GenerateUserIdentityAsync(user, manager),
            getUserIdCallback: id => id.GetUserId<int>())
    }
});

app.UseNtlmAuthentication(new NtlmAuthenticationOptions
{
    AuthenticationType = string.Format("NTLM_profile-{0}", profileId),
    CallbackPath = new PathString(string.Format("/signin-ntlm-{0}", profileId)),
    Filter = (windowsIdentity, options) =>
    {
        if (string.IsNullOrWhiteSpace(profileAuth.Ntlm.DomainGroupNameFilter))
        {
            return true;
        }

        var strippedGroupFilter = profileAuth.Ntlm.DomainGroupNameFilter.Replace("\\", "");
        return windowsIdentity.Name.StartsWith(string.Format("{0}\\", strippedGroupFilter));
    },
    OnCreateIdentity = (windowsIdentity, options) =>
    {
        // If the name is something like DOMAIN\username then
        // grab the name part (and what if it looks like username@domain?)
        var parts = windowsIdentity.Name.Split(new[] { '\\' }, 2);
        string shortName = parts.Length == 1 ? parts[0] : parts[parts.Length - 1];

        var identity = new ClaimsIdentity(options.SignInAsAuthenticationType);
        identity.AddClaims(new []
        {
            new Claim(ClaimTypes.NameIdentifier, windowsIdentity.User.Value, null, options.AuthenticationType),
            new Claim(ClaimTypes.Name, shortName), 
            new Claim(ClaimTypes.Sid, windowsIdentity.User.Value)
        });

        return identity;
    }
});
```

I've modified the AuthenticationType and CallbackPaths because I am setting this up in a multi-tenant environment where each "profile" could enable or disable this feature.

Should I be setting the "Windows Authentication" project setting to "Enabled" for this? I doubt I'd need to do that since the Interop class does a lot of the heavy lifting...

Any assistance would be greatly appreciated!

**Comment by pysco68** [comment]
Hello Josh, I'll look into you issue in the next days, I was on vacation the last month, so sorry for the delay!

**Comment by jpsullivan** [comment]
No worries about the delay! I appreciate you giving things a look though. Sadly I couldn't ever get things working. Haha I tried just about everything. Nothing looked out of place while stepping through either.

**Comment by pysco68** [comment]
Hi again Josh,

I looked at the code you provided, and on a first sight it looks perfectly right to me. Still I see some possible issues, so let me ask some questions. The first one I have is, what are you hosting your OWIN application in? If it is IIS (or any HTTP server/proxy in front of your application) have you made sure it does not process the NTLM/Kerberos stuff? (this answers your question about the Windows Authentication setting in the project; it should be off, as this is just a UI tuning some of the environments settings)

**Comment by jpsullivan** [comment]
I tested with both IISExpress (straight through VS) and a local IIS instance, and both ended up giving me the same results. And yeah, as you mentioned, there should never have been a need to enable Windows Authentication so I never did.

I should also mention that I did manage to get this working, albeit with a different library. https://www.nuget.org/packages/OWIN-MixedAuth/ to be specific. There was one thing that I did notice while setting that package up, though: It needed to be registered after any middleware that uses the `PipelineState.Authenticate` pipeline state as it relies on `PipelineState.PostAuthenticate`. I had to shuffle a few things around to get that working correctly. Do you think your library would need a similar disclaimer?

**Comment by pysco68** [comment]
Well I guess that in your application scenario using that other library is not a bad idea! In fact this OWIN middleware was designed with another case in mind that involved the impossibility to rely on either HttpListener (no WebSockets on Server 2008 R2) nor IIS (for other application specific policy).

I've used it successfully with both Nowin (which was the host I designed the library for) and Kestrel lately.
Btw. I never considered any IIS related things in the library as I was never meant to be used in conjunction with IIS (as both IIS and IISExpress support windows authentication on their own)

**Comment by jpsullivan** [comment]
Gotcha, gotcha. Makes sense! The reason we were exploring these sorts of avenues was mainly because we wanted to toggle each authentication provider. One setup may use SAML or OAuth while another chooses to use NTLM. Doing so restricts us from using IIS' Windows Authentication setting.

Thanks again for reaching out!

**Comment by pysco68** [comment]
You're welcome!

Regarding your requirement, sure, that makes sense! If I find some spare time in the next weeks I'll try to setup my lib behind IIS or IIS Ex for a few hours. If I find out anything I'll let you know!

In the meanwhile I'll close this issue if you don't mind(?)

**Comment by jpsullivan** [comment]
Nope not at all. In fact I'll do it for you ;)

Feel free to reopen though if you have any questions!
