### ISSUE TITLE
IOwinRequest in OnCreateIdentity callback

### ISSUE THREAD

**Issue by pgunya** [pysco68/Pysco68.Owin.Authentication.Ntlm#13]
Hi pysco68,

Is it possible to add IOwinRequest to OnCreateIdentity callback (like in Filter expression)?
I have a custom UserManager instance in request which I need to access when creating ClaimsIdentity.

Thank you!

**Comment by pysco68** [comment]
Hi,

I see no harm in doing so. I'm a bit busy at the moment, so it may take a few days until I find some time.

Sincerely Pysco68

**Comment by pysco68** [comment]
Note: The nuget package was updated too
