### ISSUE TITLE
Why Owin.Extensions and Owin.Types are referenced?

### ISSUE THREAD

**Issue by lukas-ais** [pysco68/Pysco68.Owin.Authentication.Ntlm#14]
Owin.Extensions and Owin.Types are referenced. But I did not found any usage.
If I remove these packages the project can be build and the test succeed.
Can we removed them?

**Comment by pysco68** [comment]
Hi, thank you for your report. These references must be dev-time leftovers. I just published v1.0.5 that fixes the small issue. Thank you for reporting ;)

**Comment by lukas-ais** [comment]
Thanks.
You are very fast!
