### ISSUE TITLE
Configuration of CallbackPath not working as expected

### ISSUE THREAD

**Issue by lukas-ais** [pysco68/Pysco68.Owin.Authentication.Ntlm#15]
I've tried to use configuration for CallbackPath to get custom URL at all.
But the login fails, I get (nearly) endless redirect (seen in Fiddler).
I've created a new unit test according current code base.
Please help to either fix the code or fix the test.

```csharp
[Test]
public async void ImplicitLogIn_CustomCallbackPath_Successful()
{
    var handler = new HttpClientHandler 
    { 
        AllowAutoRedirect = true, 
        Credentials = CredentialCache.DefaultNetworkCredentials
    };
    WebApplication.Options.CallbackPath = PathString.FromUriComponent("/My-SignIn");

    var client = new HttpClient(handler);            
    client.BaseAddress = this.BaseAddress;
            
    var response = await client.GetAsync("/api/test").ConfigureAwait(false);
    Assert.AreEqual(HttpStatusCode.OK, response.StatusCode, "Http status is incorrect");

    var result = await response.Content.ReadAsAsync<string>().ConfigureAwait(false);
    var currentUserName = Environment.UserName;
    Assert.AreEqual(currentUserName, result);            
}
```

**Comment by pysco68** [comment]
Hi Lukas,

Assuming you're trying to combine NTML Authentication with the CookieAuthentication middleware, you must take care of the redirections the cookie middleware might fire. For that reason the `IOwinRequest.IsNtlmAuthenticationCallback()` extension can take a parameter where you can supply the customized callback path.

Best you take a look at issue #7 which contains a full example in the last comments.

I hope that this helps

**Comment by lukas-ais** [comment]
Thanks, this is somehow unexpected but there is - maybe - no other solution.
More I think, the documentation, you extended while answering previous issue, should note:
"... IsNtlmAuthenticationCallback **shall** be used ...".
