### ISSUE TITLE
The identity in RequestContext.Principal.Identity does not provide domain name

### ISSUE THREAD

**Issue by lukas-ais** [pysco68/Pysco68.Owin.Authentication.Ntlm#16]
Implementing an `ApiController` I get a member `this.RequestContext`.
This provides the identity of the authorized user.

This identity, created based on ApplicationCookie (?), does not provide the domain name anymore, but only the user name.
I guess this is due to code in `Pysco68.Owin.Authentication.Ntlm.NtlmAuthenticationHandler.AuthenticateCoreAsync`. The identity is created and claims are added. For the `ClaimTypes.Name` only the short name is given. Instead the domain name (extracted before) shall be provided somehow, e.g. just as `ClaimTypes.Name`.

**Comment by pysco68** [comment]
Hi Lukas,

Sorry, but I read your issue three times, and fail to see what your issue is. You're stating a number of facts, but none seem to be an *error* to me. What behaviour do you expect, or what exactly are you trying to achieve?

**Comment by lukas-ais** [comment]
I expect the domain name with in the user name: "<DOMAIN>\<USERNAME>". This is what windows is creating initially.
I get "<USERNAME>", without the domain name, neither in any other property of the identity instance.

**Comment by pysco68** [comment]
I still don't fully get what the issue is, but would like to point out the `OnCreateIdentity` callback where you can customize the claims etc... look at the last code block in README.MD

**Comment by lukas-ais** [comment]
Ok, thanks. This way I change the default behavior.
I'm just wondering on the default. Why the default does not provide domain name in the created identity?

**Comment by pysco68** [comment]
Well, mainly because this wasn't a requirement. I developed the NTLM authentication provides in a situation with mixed logins (intranet / extranet) and users tend to not be comfortable with having to type in their FQ domain user name when not connecting from within the realm. Plus in most situations the domain part is just implicitly a constant.
