### ISSUE TITLE
when to send challenge with SignalR?

### ISSUE THREAD

**Issue by BrannonKing** [pysco68/Pysco68.Owin.Authentication.Ntlm#2]
Can you help me knowing how to use this Ntlm authentication with Owin-hosted SignalR? I need to know when to send the challenge. I also need to know if it should use cookies or authenticate every time. Also, I'm using the SignalR .NET client (not a web browser).

**Comment by BrannonKing** [comment]
Actually, I think I got it working. Apparently cookies are required. In my own middleware (that runs after the Ntlm middleware)  I do this:

```csharp
if (Request.User == null)
{
	Request.Context.Authentication.Challenge(new AuthenticationProperties{RedirectUri = Request.Uri.ToString()}, CookieAuthenticationDefaults.AuthenticationType, NtlmAuthenticationDefaults.AuthenticationType);
	return null;
}
```

**Comment by pysco68** [comment]
Yeah, this NTLM authentication middleware hooks into the normal ASP.NET identity 2.0 call chain. It basically boils down to the same as some OAuth provider. Once your client has the cookie, authenticating over SignalR should work flawlessly.
