### ISSUE TITLE
Feature request: give me a hook for rejecting particular users

### ISSUE THREAD

**Issue by BrannonKing** [pysco68/Pysco68.Owin.Authentication.Ntlm#3]
I would like the ability to reject specific users according to my own criteria. In other words, the users are valid domain users, but I don't want to authenticate them. Can we get a callback for this? In addition to the Identity object, I would need enough information to determine if the request came from the local machine.

**Comment by pysco68** [comment]
I'll have a look at this when I get some time, thanks for the request!

Btw. If you'd like to have it quicker, just grab the sources and make a pull request. It should come to offer a callback in the  NtlmAuthenticationOptions class and to check it within NtlmAuthenticationHandler somewhere around line 78.

**Comment by BrannonKing** [comment]
I see how this can be done. I'll put in a pull request early next week.

**Comment by BrannonKing** [comment]
I've checked the change into my fork. You can take a look. I'm going to wait on the pull request until it's in my actual product just to make sure I don't need anything else. That will probably be another week at least.

**Comment by pysco68** [comment]
Hello Brannon, any news on the changes? I think I'll have time to do the merging this weekend.

**Comment by BrannonKing** [comment]
The pull request is in.
