### ISSUE TITLE
Virtual Directory CallbackPath

### ISSUE THREAD

**Issue by mathewbergt** [pysco68/Pysco68.Owin.Authentication.Ntlm#7]
When I run this app under IIS Express (`http://localhost:<port>`) NTLM authentication works properly. The 302 response after creating the authentication challenge contains the proper NTLM authentication sign-in path in the `Location` header, and the browser includes the `Authorization: NTLM <token>` header when making the request to `/authentication/ntlm-signin?state=<state_id>`. 

I am running into problems however when attempting to run the app from Local IIS 7.5 under a virtual directory like so: `http://localhost/myapp/`

In NtlmAuthenticationOptions I set 
```C#
CallbackPath = "/myapp/authentication/ntlm-signin"
```
which is necessary to find the correct login path.

The problem seems to be that the `Authorization: NTLM <token>` header is missing from the request to `/myapp/authentication/ntlm-signin`, and so a response containing the `WWW-Authenticate: NTLM` header is returned. For some reason the browser is not including the Authorization token in its request to NTLM authenticate.

Am I possibly missing a step in the IIS configuration? Or maybe this could be related to the [Double Hop Authentication issue](http://blogs.msdn.com/b/besidethepoint/archive/2010/05/09/double-hop-authentication-why-ntlm-fails-and-kerberos-works.aspx)?

**Comment by mathewbergt** [comment]
Nevermind, I seem to have resolved this issue. I was setting my CookieAuthenticationOptions like so:

``` C#
new CookieAuthenticationOptions()
{
    AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
    LoginPath = new PathString("/account/login"),
    Provider = new CookieAuthenticationProvider()
    {
        OnApplyRedirect = ctx =>
        {
            if (!ctx.Request.IsNtlmAuthenticationCallback())
            {
                ctx.Response.Redirect(ctx.RedirectUri);
            }
        }
    }
}
```

The problem seemed to be specifying the `LoginPath`. When I removed this option, everything worked correctly. Perhaps it's a cross-origin type issue related to specifying the `CallbackPath` PathString with the virtual directory (i.e. `<appname>/authentication/ntlm-signin`), whereas the `LoginPath` did not contain the virtual directory (i.e. `/account/login`).

**Comment by mathewbergt** [comment]
A follow up on this issue and how I actually ended up resolving it... Since I specified a `CallbackPath` in the `NtlmAuthenticationOptions` I also needed to call `IsNtlmAuthenticationCallback` with the `redirectPath` overload in the following manner:

``` C#
OnApplyRedirect = ctx =>
{
    if (!ctx.Request.IsNtlmAuthenticationCallback(CallbackPath))
    {
        ctx.Response.Redirect(ctx.RedirectUri);
    }
}
```

If `CallbackPath` is not specified then `IsNtlmAuthenticationCallback` makes the comparison using the `NtlmAuthenticationOptions.DefaultRedirectPath` (`/authentication/ntlm-signin`), which does not work for an app under a virtual directory (`/<virtual_directory>/authentication/ntlm-signin`).

This could be a helpful tip to add to the documentation for those running apps under virtual directories.

**Comment by pysco68** [comment]
It sure would be helpful, I'll try to take care of this asap!

Thank you very much for the follow-up!

**Comment by pysco68** [comment]
Added note: 901c8c7b88c7826592791fd92ff74ad8b5584e44

**Comment by los93sol** [comment]
I'm having this same issue, but when I drop LoginPath from UseCookieAuthentication then it doesn't attempt to log the user in.

**Comment by los93sol** [comment]
Finally figured out how to do this and it should work dynamically....

        public void Configuration(IAppBuilder app)
        {
            var urlHelper = new UrlHelper(HttpContext.Current.Request.RequestContext);

            app.SetDefaultSignInAsAuthenticationType(DefaultAuthenticationTypes.ApplicationCookie);

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                LoginPath = new PathString("/Login"),
                Provider = new CookieAuthenticationProvider()
                {
                    OnApplyRedirect = ctx =>
                    {
                        if (!ctx.Request.IsNtlmAuthenticationCallback(new PathString(urlHelper.Action("authentication", "ntlm-signin"))))
                        {
                            ctx.Response.Redirect(ctx.RedirectUri);
                        }
                    }
                }
            });

            app.UseNtlmAuthentication(new NtlmAuthenticationOptions()
            {
                CallbackPath = new PathString(urlHelper.Action("authentication", "ntlm-signin"))
            });
        }
