### ISSUE TITLE
Sample using this Nuget package

### ISSUE THREAD

**Issue by kiranlpatel** [pysco68/Pysco68.Owin.Authentication.Ntlm#8]
Hi,

could you please provide complete sample as .sln file using this package for NTLM authentication, I tried my own but it was giving compile time error, actually I am new to OWIN authentication.

Thanks.

**Comment by pysco68** [comment]
Hello,

sorry I have missed your issue. You can have a look at the "Test" solution in this repository (https://github.com/pysco68/Pysco68.Owin.Authentication.Ntlm/tree/master/src/Pysco68.Owin.Authentication.Ntlm.Tests) for details. 

It's kind-of the minimum working solution.

You'll have to deal with hosting the OWIN application etc on your own however. There are plentiful of great tutorials on that topic on asp.net => http://www.asp.net/web-api/overview/hosting-aspnet-web-api

Good luck!
